test/syagi.txt
=> added world

Makefile, include/minishell.h, include/variable/env.h, include/variable/var.h, src/variable/env.c
色々名前が微妙ですが、shell変数、環境変数の構造体を作成しました。
pipeを作る時にenvpが必要なため、minishell構造体の中に
char **envpというメンバを追加していますが、これは環境変数の機能が完成したら削除する予定です。
これに関連して、env.cの中に仮として下記関数を作成しました。
```
void	set_envp(t_minishell *minish, char **envp)
char	**get_envp(t_minishell *minish)
```
=> 変数関連のプロトタイプを作成

.gitignore, Makefile
本家のreadlineのソースコードをダウンロードしてきて、コンパイルする処理をMakefileに追加しました。
=> readline追加

.gitignore, Makefile, test/unit/CMakeLists.txt, test/unit/src/hello_test.cpp, test/unit/src/parser/lexer.cpp
google testを追加しました。
```
make unit_test
```
とすると、単体テストを実行できます。
まだ、すべてのテストは書いていませんが、
テンプレート的なところまでできたので、一旦プルリクを出しました。
=> Google test追加

.vscode/launch.json, Makefile, include/minishell.h, include/variable/env.h, include/variable/var.h, src/main.c, src/minishell.c, src/variable/env.c, src/variable/var.c, test/unit/CMakeLists.txt, test/unit/src/variable/env.cpp, test/unit/src/variable/var.cpp
- get, setする関数を作成
- set時は、typeも引数を取るようにした（必要ないかも）
=> envを構造体varに突っ込む

.gitignore, .vscode/launch.json, Makefile, include/builtin/builtin.h, include/parser/node.h, libft/Makefile, libft/ft_strcmp.c, libft/libft.h, src/builtin/builtin.c, src/builtin/builtin_cd.c, src/builtin/builtin_echo.c, src/builtin/builtin_env.c, src/builtin/builtin_exit.c, src/builtin/builtin_export.c, src/builtin/builtin_pwd.c, src/builtin/builtin_unset.c, src/exec/exec.c, src/exec/pipe.c, src/exec/process.c, src/parser/lexer.c, src/parser/parser.c, src/parser/prompt.c, src/variable/env.c, src/variable/var.c, test/unit/CMakeLists.txt
builtinのモックを作成して、pipeを修正しました。
ついでに、下記修正しました。
- デバッグログがいっぱい出すぎてしまっているので、一旦コメントアウトしました。
- 単体テストの実行ファイルの出力先を test/unit/testBin -> test/unit/built/bin に変更しました。
=> builtinモック作成

src/exec/pipe.c
=> 子プロセスのbuiltinをまとめてexit 

src/variable/env.c, src/variable/var.c, test/unit/src/variable/env.cpp
set_envpでkeyを更新する時の条件がおかしかった
- 修正前
```
if (ft_strncmp(current->key, key, ft_strlen(current->key)) == 0)
```
- 修正後
```
if (ft_strncmp(current->key, key, ft_strlen(key)) == 0)
```
=> #34　環境変数の設定バク対応　

include/builtin/builtin.h, src/builtin/builtin_exit.c, test/e2e/case/builtin_exit.in
=> Builtin_exit

include/variable/var.h, src/variable/var.c, test/unit/src/variable/var.cpp
```
bool				is_var_declaration(const char *str, size_t n);
```
=> 変数宣言かどうか判定する関数を追加しました

src/builtin/builtin_cd.c, test/e2e/case/builtin_cd.in
=> cdに空文字を渡した時の挙動が異なる #57 対応

include/builtin/builtin.h, include/variable/env.h, include/variable/var.h, src/builtin/builtin_cd.c, src/builtin/builtin_export.c, src/variable/env.c, src/variable/var.c, test/e2e/case/builin_export.in, test/e2e/case/builtin_cd.in, test/unit/src/variable/env.cpp, test/unit/src/variable/var.cpp
=> builtin export実装

include/message/message.h, include/utils/exit_status.h, src/builtin/builtin_exit.c, src/exec/process.c, src/exec/redirect.c
#56 対応
- exit_status.hを作成
- エラー文、exit_statusを修正
=> 存在しないコマンドを打った時のエラー文に差分あり #56

include/message/message.h, include/parser/heredoc.h, include/utils/exit_status.h, include/utils/minishell_error.h, src/parser/expansion.c, src/parser/heredoc.c, src/parser/parser.c, src/utils/minishell_error.c
parser, heredoc, expansion周りだけmallocエラー時の処理を実装しました。
修正範囲が大きくなりすぎなので、一旦プルリク出します。
=> mallocエラー処理

include/message/message.h, include/utils/utils.h, include/variable/env.h, src/builtin/builtin_export.c, src/utils/utils.c, src/variable/env.c, test/unit/src/variable/env.cpp
fix #53
- keyの一覧を取得する関数作成
- keyの一覧を昇順にsortする関数作成
=> export 引数がない場合のソート #53 対応

include/builtin/builtin.h, include/message/message.h, include/minishell.h, include/utils/minishell_error.h, src/builtin/builtin.c, src/exec/pipe.c, src/exec/redirect.c, src/minishell.c, src/parser/expansion.c, src/parser/lexer.c, src/parser/parser.c, src/utils/minishell_error.c
=> マクロ関数を通常の関数に修正しました。

src/builtin/builtin_exit.c
=> free後にメモリアクセスを修正

.github/workflows/test.yml, src/builtin/builtin_exit.c, test/e2e/case/builtin_env.in, test/e2e/case/builtin_exit.in
- node->wait_statusにも終了コードを設定
- e2e exitテストケースを追加
fix #101
=> exitの動作がbashと異なる #101

Makefile, include/builtin/builtin_exit.h, src/builtin/builtin_exit.c, src/builtin/builtin_exit_print.c
新規ファイル作成
- builtin_exit.h
- builtin_exit_print.c
=> norm対応 builtin_exit

Makefile, include/parser/heredoc.h, include/parser/struct_heredoc.h, src/exec/redirect.c, src/parser/heredoc_input.c, src/parser/heredoc_output.c, src/parser/heredoc_utils.c
バグが見つかりましたが、一旦normだけ対応しました。
#112 これの対応をお願いしていいですか？
=> heredoc.cのnorm対応

src/exec/find_path.c, test/e2e/case/find_path.in
=> norm対応(find_path.c)

.github/workflows/test.yml, Makefile, libft/ft_split2.c, libft/libft.h
- libftに追加した関数がNormエラーになっていたので修正しました。
- 自動テストにNormを追加しました。（今はまだlibftだけNormチェックしています。）
=> Norm対応(ft_split2.c)

Makefile, include/parser/node.h, include/utils/utils.h, src/parser/node.c, src/parser/parser_command.c, src/utils/utils.c
fix #121
argvが100個固定にしていたものを修正しました。
node.h
```
```
を3などに変更して（2以上必須）、
argvを再mallocできていることを確認しました。
=> argv可変長に修正

Makefile, include/variable/env.h, include/variable/var.h, src/variable/var.c, src/variable/var_check.c, src/variable/var_edit.c
- Makefileのnormをlibft, include, srcを対象にしました。
=> norm対応 var
